### ISSUE TITLE
Setup Unity cache on Travis

### ISSUE THREAD

**Issue by eppz** [watson-developer-cloud/unity-sdk#309]
Hi, this is more of a **question** than an isssue (you may label it).

I have this Travis setup: https://travis-ci.org/eppz/Unity.Test.eppz/builds/325910431

Basically I can install Unity just fine from command line, also I can cache it using Travis cache.
But if I want to run Unity that has recovered from cache, the execution of Unity.app just hangs on for 10 minutes, then it is shut down by Travis timeout.

Is there any additional step I should take when caching a Unity installation?

The [full travis yml](https://github.com/eppz/Unity.Test.eppz/blob/master/.travis.yml) goes like this:
```
os: osx
language: generic
cache:
  timeout: 900
  directories:
    - /Applications/Unity
install:
  - sudo python2 .scripts/install-unity.py --package Unity 2017.1.1f1
before_script:
  - sudo chmod -R a+rwx /Applications/Unity
script:
  - .scripts/test $TRAVIS_BUILD_DIR eppz.TestResult.xml
```

And a failing build (when Unity installation is recovered from cahce) is like this: https://travis-ci.org/eppz/Unity.Test.eppz/builds/325883867
